### ISSUE TITLE
Setup-keg fails beause of ::add-path::, which is deprecated.

### ISSUE THREAD

**Issue by ROCKTAKEY** [conao3/setup-keg#3]
kegやsetup-kegのメンテナンス、ありがとうございます。

表題の通りで、setup-kegが落ちてしまいます。
このあたり詳しく知らないのですが、見た限りではおそらくcaskの [issue](https://github.com/conao3/setup-cask/issues/6)と同じ原因だと思います。

log: https://github.com/ROCKTAKEY/auto-save-async/runs/1484278139?check_suite_focus=true#step:4:35

**Comment by conao3** [comment]
報告ありがとうございます。こちらも直さないとでしたね。
更新してみましたが、なんか落ちてます;
とりあえず@actionsの方はエラーでなくなってると思うのでマージしましたが、問題があれば教えてください。

**Comment by ROCKTAKEY** [comment]
早速のご対応ありがとうございます。
無事動くようになりました。今のところ問題はなさそうです。
またなにかあれば連絡します。
