### ISSUE TITLE
wrong-type-argument stringp nil

### ISSUE THREAD

**Issue by ROCKTAKEY** [conao3/setup-keg#8]
条件は分からないのですが、actionsでもテストと同様に、表題のエラーで落ちることがあるようです。

CI of grugru:
[Log](https://github.com/ROCKTAKEY/grugru/runs/1496718174?check_suite_focus=true#step:4:36)
[Source](https://github.com/ROCKTAKEY/grugru/blob/master/.github/workflows/CI.yml)

一方こちらでは落ちていません。

CI of auto-save-async:
[Log](https://github.com/ROCKTAKEY/auto-save-async/runs/1496718059#step:4:35)
[Source](https://github.com/ROCKTAKEY/auto-save-async/blob/master/.github/workflows/CI.yml)

かなり不思議なのですが、setup-keg以前の動作が全く同じなのにも関わらず、何度Re-runしてもgrugruのほうでだけ失敗してauto-save-asyncのほうは成功します。

**Comment by ROCKTAKEY** [comment]
原因が分かったので付記しておきます。

Kegファイルがないのが原因でした。このとき、`keg-file-dir`、`keg-home-dir`、`keg-elpa-dir`が順にnilを返すため、`keg-initialize`において`package-user-dir`がnilに設定されてしまいます。`package-initialize`はその値がnilでないことを確認せずに`package-user-dirを`file-directory-p`に渡すので、ここでエラーを吐いています。

**Comment by yamashita-optarc** [comment]
なるほど。実際Kegファイルはなくてもデフォルトで仮定してもいいと思います。
(sourceはelpaとmelpa、パッケージファイルはそれっぽいElispファイルと仮定する)
ただ、その処理はまだ実装できていません。。

**Comment by conao3** [comment]
なるほど。実際Kegファイルはなくてもデフォルトで仮定してもいいと思います。
(sourceはelpaとmelpa、パッケージファイルはそれっぽいElispファイルと仮定する)
ただ、その処理はまだ実装できていません。。

**Comment by ROCKTAKEY** [comment]
たしかに、それはそうかもしれないですね。
暫定的な解決としては、`keg-home-dir` において、`keg-file-dir`がnilを返したときには`default-directory`を使う、とかがいいかなあと思います(Kegファイルが存在しないとversionすら表示できないのはおそらく意図しない動作だと思うので)。
